name: Keep Supabase Alive

on:
  schedule:
    # Menjalankan script setiap hari Senin dan Kamis pukul 00:00 UTC selama 3 hari sekali
    - cron: "0 0 * * 1,4"

  # Memungkinkan kita menekan tombol "Run" secara manual di GitHub
  workflow_dispatch:

jobs:
  ping-database:
    runs-on: ubuntu-latest
    steps:
      - name: Mengetuk Pintu Supabase
        run: |
          curl -X GET "${{ secrets.SUPABASE_URL }}/rest/v1/products?select=id&limit=1" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}"
